models.py, line 128: corrected 'other_use' to 'other_user'